target 'NetworkableExample (iOS)' do
  platform :ios, '15.4'
  use_frameworks!
  pod 'Networkable', :path => '../'
end

target 'NetworkableExample (macOS)' do
  platform :osx, '12.3'
  use_frameworks!
  pod 'Networkable', :path => '../'
end
