target 'NetworkableExample (iOS)' do
  platform :ios, '16'
  use_frameworks!
  pod 'Networkable', :path => '../'
end

target 'NetworkableExample (macOS)' do
  platform :osx, '12.6'
  use_frameworks!
  pod 'Networkable', :path => '../'
end