name: Swift

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkouts project
      uses: actions/checkout@v3
    - name: Installs latest stable Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Builds
      run: swift build -v
    - name: Runs tests
      run: swift test -v